/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutIcon: typeof import('@nutui/nutui-taro')['Icon']
    NutInfiniteLoading: typeof import('@nutui/nutui-taro')['InfiniteLoading']
    NutLoading: typeof import('@nutui/nutui-taro')['Loading']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
    NutNavBar: typeof import('@nutui/nutui-taro')['NavBar']
    NutPullRefresh: typeof import('@nutui/nutui-taro')['PullRefresh']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
  }
}
